@accountId = 695a7f39fbc7fac1166afa45
@accountPath = /v2/accounts

# Get account balance
{{monoBaseUrl}}{{accountPath}}/{{accountId}}/balance
Accept: application/json
mono-sec-key: {{monoConnectSecretKey}}
Content-Type: application/json

###
# Get accounts
{{monoBaseUrl}}{{accountPath}}
Accept: application/json
mono-sec-key: {{monoConnectSecretKey}}
Content-Type: application/json

###
# Get account details
{{monoBaseUrl}}{{accountPath}}/{{accountId}}
Accept: application/json
mono-sec-key: {{monoConnectSecretKey}}
Content-Type: application/json

###
# Get account transactions
{{monoBaseUrl}}{{accountPath}}/{{accountId}}/transactions
?start=28-12-2025
&end=11-01-2026
&narration=
&type=
&paginate=true
&limit=10
Accept: application/json
mono-sec-key: {{monoConnectSecretKey}}
Content-Type: application/json
