# Install RestClient for VSCode to run this file 

@baseUrl = http://localhost:3000

###
# Get authorized individual user data
GET {{baseUrl}}/api/v1/individuals/me
Authorization: Bearer {{accessToken}}

###
# Toggle MFA
POST {{baseUrl}}/api/v1/individuals/mfa
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "mfaEnabled": false
}
