# Install RestClient for VSCode to run this file 

@baseUrl = http://localhost:3000

###
# Get tier 1 status
GET {{baseUrl}}/api/v1/kyc/tier1
Authorization: Bearer {{accessToken}}

###
# Verify tier 1
POST {{baseUrl}}/api/v1/kyc/tier1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "photoId": "https://example.com/photo-id.jpg",
  "firstName": "Ernest",
  "middleName": "Ojewolo",
  "lastName": "Irabor",
  "gender": "m",
  "dob": "1989-02-16",
  "nin": "12345678901",
  "street": "123 Main St",
  "city": "Ikeja",
  "state": "Lagos"
}

###
# Get tier 2 status
GET {{baseUrl}}/api/v1/kyc/tier2
Authorization: Bearer {{accessToken}}

###
# Verify tier 2
POST {{baseUrl}}/api/v1/kyc/tier2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "idType": "voter's ID card",
  "govtId": "12345678901",
  "idUrl": "https://example.com/govt-id.jpg"
}

###
# Get tier 3 status
GET {{baseUrl}}/api/v1/kyc/tier3
Authorization: Bearer {{accessToken}}

###
# Verify tier 3 address proof (part 1)
POST {{baseUrl}}/api/v1/kyc/tier3/address-proof
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "proofType": "utility bill",
  "addressProof": "https://example.com/address-proof.jpg"
}

###
# Verify tier 3 liveness selfie (part 2)
POST {{baseUrl}}/api/v1/kyc/tier3/live-selfie
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "liveSelfie": "https://example.com/live-selfie.jpg"
}
