# Install RestClient for VSCode to run this file 

@baseUrl = http://localhost:3000
@formBoundary = formDataBoundary

###
# Upload passport photo
POST {{baseUrl}}/api/v1/kyc/upload/passport-photo
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary={{formBoundary}}

--{{formBoundary}}
Content-Disposition: form-data; name="passportPhoto"; filename="sample.jpeg"
Content-Type: image/jpeg

< ../files/sample.jpeg
--{{formBoundary}}--

###
# Upload government ID
POST {{baseUrl}}/api/v1/kyc/upload/govt-id
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary={{formBoundary}}

--{{formBoundary}}
Content-Disposition: form-data; name="govtId"; filename="sample.jpeg"
Content-Type: image/jpeg

< ../files/sample.jpeg
--{{formBoundary}}--

###
# Get tier 1 status
GET {{baseUrl}}/api/v1/kyc/tier1
Authorization: Bearer {{accessToken}}

###
# Verify tier 1
POST {{baseUrl}}/api/v1/kyc/tier1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "passportPhoto": "http://localhost:3900/bun-mobile-banking/kyc/passport-photos/individual-019b6cda-1d16-789c-9595-2809ecf7c707.jpeg",
  "firstName": "Samuel",
  "middleName": "Nomo",
  "lastName": "Olamide",
  "gender": "m",
  "dob": "01-06-2020",
  "nin": "12345678901",
  "street": "123 Main St",
  "city": "Ikeja",
  "state": "Lagos"
}

###
# Get tier 2 status
GET {{baseUrl}}/api/v1/kyc/tier2
Authorization: Bearer {{accessToken}}

###
# Verify tier 2
POST {{baseUrl}}/api/v1/kyc/tier2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "idType": "voter's ID card",
  "govtId": "12345678901",
  "idUrl": "http://localhost:3900/bun-mobile-banking/kyc/govt-id/individual-019b6cda-1d16-789c-9595-2809ecf7c707.jpeg"
}

###
# Get tier 3 status
GET {{baseUrl}}/api/v1/kyc/tier3
Authorization: Bearer {{accessToken}}

###
# Verify tier 3 address proof (part 1)
POST {{baseUrl}}/api/v1/kyc/tier3/address-proof
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "proofType": "utility bill",
  "addressProof": "https://example.com/address-proof.jpg"
}

###
# Verify tier 3 liveness selfie (part 2)
POST {{baseUrl}}/api/v1/kyc/tier3/live-selfie
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "liveSelfie": "https://example.com/live-selfie.jpg"
}

###
# Upload address proof image
POST {{baseUrl}}/api/v1/kyc/tier3/address-proof/upload
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary={{formBoundary}}

--{{formBoundary}}
Content-Disposition: form-data; name="addressProofImage"; filename="sample.jpeg"
Content-Type: image/jpeg

< ../dev-files/sample.jpeg
--{{formBoundary}}--

###
