@baseUrl = https://api.withmono.com
@ninPath = /v3/lookup/nin
@bvnPath = /v2/lookup/bvn
@passportPath = /v3/lookup/passport
@driverLicensePath = /v3/lookup/driver_license

###
# NIN lookup
POST {{baseUrl}}{{ninPath}}
mono-sec-key: {{monoLookupSecretKey}}
Content-Type: application/json
accept: application/json

{
    "nin": "{{monoNin}}"
}

###
# Initiate BVN lookup #1
POST {{baseUrl}}{{bvnPath}}/initiate
mono-sec-key: {{monoLookupSecretKey}}
Content-Type: application/json
accept: application/json

{
    "bvn": "{{monoBvn}}"
}

###
# Verify BVN OTP #2
POST {{baseUrl}}{{bvnPath}}/verify
x-session-id: JaTDzVjQtNt2lXf389lb
mono-sec-key: {{monoLookupSecretKey}}
Content-Type: application/json
accept: application/json

{
    "method": "phone",
    "phone_number": "{{monoAlternatePhone}}"
}

###
# Fetch BVN Details #3
POST {{baseUrl}}{{bvnPath}}/details
x-session-id: JaTDzVjQtNt2lXf389lb
mono-sec-key: {{monoLookupSecretKey}}
Content-Type: application/json
accept: application/json

{
    "otp": "{{monoOtp}}"
}

###
# Lookup passport
POST {{baseUrl}}{{passportPath}}
mono-sec-key: {{monoLookupSecretKey}}
Content-Type: application/json
accept: application/json

{
    "passport_number": "{{monoIntlPassportNumber}}",
    "last_name": "{{monoIntlPassportLastName}}",
    "date_of_birth": "{{monoIntlPassportDob}}"
}

###
# Lookup driver's license
POST {{baseUrl}}{{driverLicensePath}}
mono-sec-key: {{monoLookupSecretKey}}
Content-Type: application/json
accept: application/json

{
  "license_number": "{{monoDriverLicenseNumber}}",
  "date_of_birth": "{{monoDriverLicenseDob}}",
  "first_name": "{{monoDriverLicenseFirstName}}",
  "last_name": "{{monoDriverLicenseLastName}}"
}
